import { Resizer } from "./components/Resizer";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                {/* <Resizer> */}
                {children}
                {/* </Resizer> */}
            </body>
        </html>
    );
}
